### ISSUE TITLE
Readme screenshots: Not Found

### ISSUE THREAD

**Issue by duianto** [yegortimoshenko/plain-theme#1]
The screenshots in the readme are broken, they just open pages with the text:
>Not Found

**Comment by duianto** [comment]
I found the screenshots on https://web.archive.org/

#### plain-theme-1.png
![image](https://user-images.githubusercontent.com/13420573/64511218-1f3d5380-d2e4-11e9-93c8-f0ad01f27e6a.png)
source: https://web.archive.org/web/20161013235806/https://yegortimoshenko.s3.amazonaws.com/plain-theme-1.png

#### plain-theme-2.png
![image](https://user-images.githubusercontent.com/13420573/64511229-26fcf800-d2e4-11e9-96a5-e55ba6d3615e.png)
source: https://web.archive.org/web/20161013235847/https://yegortimoshenko.s3.amazonaws.com/plain-theme-2.png

**Comment by yegortimoshenko** [comment]
Cool, thank you!

**Comment by yegortimoshenko** [comment]
Resolved in 48b37b9b19d8f1e0accbf930f30b5346cf7959fe. Again, thanks so much for recovering these images!
